CREATE TABLE IF NOT EXISTS USER
(
	userID		VARCHAR(128) NOT NULL PRIMARY KEY,
    	account		VARCHAR(128) NOT NULL UNIQUE,
    	password	VARCHAR(1024),
	name		VARCHAR(128),
	nickName	VARCHAR(128),
	phone		VARCHAR(16),
	address		VARCHAR(1024),
	postNum		VARCHAR(16),
	email		VARCHAR(128),
	oauthSource	VARCHAR(128);
	birthday	DATE,
	adminFlg	TINYINT(2) DEFAULT 0,
	certificatedFlg	TINYINT(2) DEFAULT 0,
	deliverAddress	TEXT,
	currentDeliverAddr	TEXTT,
	intro		TEXT,
	image		MEDIUMBLOB,
	point		BIGINT DEFAULT 0,
	insertDate	DATETIME NOT NULL,
	updateDate	DATETIME NOT NULL,
	delFlg		TINYINT(2) DEFAULT 0
) ENGINE=MyISAM DEFAULT CHARACTER SET=UTF8;

CREATE TABLE IF NOT EXISTS SHOP
(
	shopID		VARCHAR(128) NOT NULL PRIMARY KEY,
	dispName VARCHAR(128),
    address	VARCHAR(128),
    owner	VARCHAR(128),
    category	VARCHAR(128),
    administrator	VARCHAR(128),
    insertDate	DATETIME NOT NULL,
    updateDate	DATETIME NOT NULL,
    delFlg	TINYINT(2) DEFAULT 0,
    intro	TEXT,
    logo	VARBINARY(10240) BINARY
) ENGINE=MyISAM DEFAULT CHARACTER SET=UTF8;




