CREATE TABLE IF NOT EXISTS USER
(
	id		VARCHAR(128) NOT NULL PRIMARY KEY,
    account		VARCHAR(128) NOT NULL UNIQUE,
    password	VARCHAR(1024) NOT NULL,
	name		VARCHAR(128) NOT NULL,
	nickName	VARCHAR(128) NOT NULL,
	phone		VARCHAR(16) DEFAULT "",
	address		VARCHAR(1024) DEFAULT "",
	postNum		VARCHAR(16) DEFAULT "",
	email		VARCHAR(128) NOT NULL,
	birthday	DATE,
	adminFlg	TINYINT(2) DEFAULT 0,
	certificatedFlg	TINYINT(2) DEFAULT 0,
	deliverAddress	TEXT DEFAULT "",
	currentDeliverAddr	TEXT DEFAULT "",
	intro		TEXT DEFAULT "",
	image		MEDIUMBLOB,
	point		BIGINT DEFAULT 0,
	insertDate	DATETIME NOT NULL,
	updateDate	DATETIME NOT NULL,
	delFlg		TINYINT(2) DEFAULT 0
) ENGINE=MyISAM DEFAULT CHARACTER SET=UTF8;
CREATE TABLE IF NOT EXISTS SHOP
(
	id		VARCHAR(128) NOT NULL PRIMARY KEY,
	name	VARCHAR(128) NOT NULL,
    address	VARCHAR(128) NOT NULL,
    owner	VARCHAR(128) NOT NULL,
    category	VARCHAR(128) NOT NULL,
    administrator	VARCHAR(128) NOT NULL,
    insertDate	DATETIME NOT NULL,
    updateDate	DATETIME NOT NULL,
    delFlg	TINYINT(2) DEFAULT 0,
    intro	TEXT DEFAULT "",
    logo	VARBINARY(10240) BINARY
) ENGINE=MyISAM DEFAULT CHARACTER SET=UTF8;
CREATE TABLE IF NOT EXISTS PRODUCT
(
	id		VARCHAR(128) NOT NULL PRIMARY KEY,
	name	VARCHAR(128) NOT NULL,
	shopId 	VARCHAR(128) NOT NULL,
	category	VARCHAR(128) NOT NULL,
    intro	TEXT DEFAULT "",
    detail  TEXT DEFAULT "",
    originalPrice FLOAT(16) NOT NULL,
    newPrice FLOAT(16) NOT NULL,
    discountRate FLOAT(8) NOT NULL,
    disBeginDate DATETIME NOT NULL,
    disEndDate DATETIME NOT NULL,
    insertDate	DATETIME NOT NULL,
    updateDate	DATETIME NOT NULL,
    delFlg	TINYINT(2) DEFAULT 0,
   	image		MEDIUMBLOB,
    count  BIGINT(16) NOT NULL,
    saledCount BIGINT(16) NOT NULL,
    evaluation TEXT DEFAULT ""
) ENGINE=MyISAM DEFAULT CHARACTER SET=UTF8;
