CREATE TABLE IF NOT EXISTS USER
(
	userID		VARCHAR(128) NOT NULL PRIMARY KEY,
    	account		VARCHAR(128) NOT NULL UNIQUE,
    	password	VARCHAR(1024),
	name		VARCHAR(128),
	nickName	VARCHAR(128),
	phone		VARCHAR(16),
	address		VARCHAR(1024),
	postNum		VARCHAR(16),
	email		VARCHAR(128),
	oauthSource	VARCHAR(128),
	birthday	DATETIME,
	adminFlg	TINYINT(2) DEFAULT 0,
	certificatedFlg	TINYINT(2) DEFAULT 0,
	gender		TINYINT(3) DEFAULT 2,
	deliverAddress	TEXT,
	currentDeliverAddr	TEXT,
	intro		TEXT,
	image		VARCHAR(1024),
	point		BIGINT DEFAULT 0,
	idCard		VARCHAR(1024),
	insertDate	DATETIME NOT NULL,
	updateDate	DATETIME NOT NULL,
	delFlg		TINYINT(2) DEFAULT 0
) ENGINE=MyISAM DEFAULT CHARACTER SET=UTF8;

CREATE TABLE IF NOT EXISTS SHOP
(
	shopID		VARCHAR(128) NOT NULL PRIMARY KEY,
	dispName VARCHAR(128),
    address	VARCHAR(128),
    owner	VARCHAR(128),
    category	VARCHAR(128),
    administrator	VARCHAR(128),
    insertDate	DATETIME NOT NULL,
    updateDate	DATETIME NOT NULL,
    delFlg	TINYINT(2) DEFAULT 0,
    intro	TEXT,
    logo	VARCHAR(1024)
) ENGINE=MyISAM DEFAULT CHARACTER SET=UTF8;




